### ISSUE TITLE
re: installation from github.

### ISSUE THREAD

**Issue by xenmind** [JQVeenstra/arfima#1]
Hi,
Great package. I tried updating from the cran version, but get the following error:

 install_github("JQVeenstra/arfima")
Downloading GitHub repo JQVeenstra/arfima@master
from URL https://api.github.com/repos/JQVeenstra/arfima/zipball/master
Installing arfima
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/xen/AppData/Local/Temp/RtmpaWWscB/devtools10907baf774b/JQVeenstra-arfima-acd130b"  \
  --library="C:/Users/xen/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'arfima' ...
Error : Invalid DESCRIPTION file

Malformed maintainer field.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package 'arfima'

Gavin.

**Comment by JQVeenstra** [comment]
Glad you like the package.  I don't think there should be much difference between 1.6-5 and 1.6-2 - although to be honest I'm surprised that 1.6-5 is not on CRAN.  I had thought I had put it there.

I'm currently away from my dev machine - I will look into this ASAP.

**Comment by JQVeenstra** [comment]
Ok - the fix was required because of some things that have seemingly changed within CRAN's requirements from a GitHub install.  Something kind of silly, and I don't like the change, but...
