### ISSUE TITLE
Haslett-Raftery estimation

### ISSUE THREAD

**Issue by kaoruoshita** [JQVeenstra/arfima#3]
Hi,

Is it possible to select estimation method of Haslett-Raftery when we call arfima() ?

Thanks,
Kay

**Comment by JQVeenstra** [comment]
Hi Kay,

When this package was written, the point was to introduce a package that used exact likelihood method for arfima modelling.

The Haslett-Raftery method is appropriate.

My PhD supervisor kinda had a thing for exact methods, and the package was basically the computational component of my thesis. 

So, no, currently it's not possible. 

Luckily, the `fracdiff` package does use that method if you have a specific need for it.

If you can make a convincing argument for the inclusion of the method, *and* I manage to find the time and energy to add it, I'll do so. 

Cheerio,
JQ
